---
sequence:
  bedtime:
  - - lounge
    - all
    - 'off'
  - - dining
    - all
    - 'off'
  - - kitchen
    - all
    - 'off'
room:
- name: our
  device:
  - name: light
    type: D
  - name: lights
    type: D
  - name: kettle
    type: O
  - name: tv
    type: O
- name: dining
  device:
  - name: light
    type: D
  - name: lights
    type: D
- name: lounge
  device:
  - name: light
    type: D
  - name: lights
    type: D
  - name: tv
    type: O
  - name: lamp1
    type: O
  - name: lamp2
    type: O
  - name: surround
    type: O
- name: kitchen
  device:
  - name: kettle
    type: O
  - name: toaster
    type: O
  - name: radio
    type: O
  - name: socket
    type: O
calendar: 'https://www.google.com/calendar/feeds/aar79qh62fej54nprq6334s7ck%40group.calendar.google.com/public/basic'
host: 192.168.1.64
